(() => {
'use strict';
const CFG=Object.assign({apiBase:'https://wagaya-album-api.sslowdayss.workers.dev',maxFileSizeMB:50},window.ALBUM_CONFIG||{}),API=String(CFG.apiBase||'https://wagaya-album-api.sslowdayss.workers.dev').replace(/\/$/,''),DB_NAME='wagaya-album',DB_VERSION=4,ACCESS='wagaya_album_access_key';
const VIEWS=['homeView','genericAlbumView','pianoView','farmListView','farmView','strategyView','memoryListView','memoryDetailView'];
const CHECKS=[['monsters','⚔️','モンスタースレイヤー'],['fish','🐟','魚'],['cooking','🍳','料理'],['crafting','🔨','クラフト'],['walnuts','🥥','黄金のクルミ'],['obelisks','🗿','オベリスク'],['clock','🕰️','金時計'],['stardrops','⭐','スタードロップ']];
const SEED_FARMS=[
 {id:'farm-hello',name:'ハロー牧場',main:'',mama:'',eldest:'',youngest:'',year:11,note:'家族で長年遊んでいる牧場',createdAt:'2026-09-14T00:00:00Z'},
 {id:'farm-colorful',name:'カラフル牧場',main:'',mama:'',eldest:'',youngest:'',year:'',note:'',createdAt:'2026-09-14T00:00:01Z'},
 {id:'farm-plants',name:'しょくぶつ牧場',main:'長女',mama:'',eldest:'',youngest:'',year:'',note:'キャラクター名も植物縛り',createdAt:'2026-09-14T00:00:02Z'},
 {id:'farm-animals',name:'どうぶつ牧場',main:'次女',mama:'つちのこ',eldest:'うさ',youngest:'ワニ',year:'',note:'ママの「つちのこ」は、みんなから「つっちー」と呼ばれている。',createdAt:'2026-09-14T00:00:03Z'}
];
const SEED_MEMORIES=[
 {id:'memory-hello-school',farmId:'farm-hello',title:'長女が作った学校',gameYear:'',season:'',day:'',participants:['長女'],tags:['学校'],story:'長女が牧場の中に作った学校。',createdAt:'2026-09-14T00:10:00Z'},
 {id:'memory-hello-stage',farmId:'farm-hello',title:'「お嬢様と妖精」の舞台',gameYear:'',season:'',day:'',participants:['ママ','長女','次女'],tags:['舞台','イベント'],story:'長女が作った舞台。10時から公演を見ていたら18時になった。ママの入場券は、レアな「魔法のロックキャンディ」。',createdAt:'2026-09-14T00:11:00Z'},
 {id:'memory-hello-halloween',farmId:'farm-hello',title:'ハロウィンの仮装',gameYear:'',season:'秋',day:'',participants:['ママ','長女','次女'],tags:['ハロウィン','イベント'],story:'長女＝ねずみ、次女＝ネコミミ、ママ＝全身カボチャ。',createdAt:'2026-09-14T00:12:00Z'},
 {id:'memory-hello-coffee',farmId:'farm-hello',title:'次女のコーヒー屋さん',gameYear:'',season:'',day:'',participants:['ママ','次女'],tags:['お店'],story:'大量のタルを設置して、コーヒー豆を約2000個渡したのに数日でなくなった。',createdAt:'2026-09-14T00:13:00Z'},
 {id:'memory-hello-dryers',farmId:'farm-hello',title:'乾燥機だらけの地下室',gameYear:'',season:'',day:'',participants:['長女'],tags:['事件'],story:'長女の地下室はワイン熟成ではなく乾燥機だらけ。フルーツを5個ずつ大量消費する。',createdAt:'2026-09-14T00:14:00Z'},
 {id:'memory-hello-mannequin',farmId:'farm-hello',title:'朝6:30の呪われたマネキン事件',gameYear:'',season:'',day:'',participants:['ママ','長女','次女'],tags:['事件'],story:'呪われたマネキンが勝手にベッド横まで移動。姉妹を呼んでも動かせず、最終的にチェリーボムで爆破して撤去。',createdAt:'2026-09-14T00:15:00Z'},
 {id:'memory-hello-fireworks',farmId:'farm-hello',title:'次女、花火をすぐ打ち上げる',gameYear:'',season:'',day:'',participants:['次女'],tags:['イベント'],story:'次女は花火を見つけると、すぐ買って打ち上げる。',createdAt:'2026-09-14T00:16:00Z'}
];
const GUIDE=[
 {id:'guide-town',kind:'image',name:'ペリカンタウンの秘密マップ',note:'町の秘密・場所メモ',url:'./media/stardew-town-secrets.jpeg',seed:true},
 {id:'guide-gifts',kind:'image',name:'住人のプレゼント早見表',note:'住人別・好きなプレゼント',url:'./media/stardew-gifts-chart.jpeg',seed:true}
];
const S={view:'homeView',stack:[],albums:[],albumFiles:[],albumId:null,farms:[],strategies:[],memories:[],files:[],piano:[],guides:[],farmId:null,memoryId:null,tag:'all',pianoFilter:'all',viewer:[],viewerIndex:0,viewerDelete:null,viewerScope:'',cloud:false};
const $=id=>document.getElementById(id); let dbp,toastTimer;

document.addEventListener('DOMContentLoaded',init);
async function init(){bind();await loadLocal();await ensureSeeds();renderAll();if(API&&key())await syncCloud(true);show('homeView',false);updateStorage();}
function bind(){
 document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;actions[b.dataset.action]?.(b);});
 $('backButton').addEventListener('click',goBack);$('settingsButton').addEventListener('click',()=>{ $('accessKeyInput').value=key();updateStorage();$('settingsDialog').showModal();});
 document.querySelectorAll('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 document.querySelectorAll('[data-piano-filter]').forEach(b=>b.onclick=()=>{S.pianoFilter=b.dataset.pianoFilter;document.querySelectorAll('[data-piano-filter]').forEach(x=>x.classList.toggle('active',x===b));renderPiano();});
 $('albumForm').addEventListener('submit',saveAlbum);$('albumMediaForm').addEventListener('submit',saveAlbumMedia);$('farmForm').addEventListener('submit',saveFarm);$('strategyForm').addEventListener('submit',saveStrategy);$('memoryForm').addEventListener('submit',saveMemory);$('pianoForm').addEventListener('submit',savePiano);$('guideForm').addEventListener('submit',saveGuide);$('guideEditForm').addEventListener('submit',saveGuideTitle);$('settingsForm').addEventListener('submit',saveSettings);
}
const actions={
 'open-piano':()=>show('pianoView'),'open-stardew':()=>show('farmListView'),'add-album':()=>openAlbumDialog(),'open-album':b=>openAlbum(b.dataset.id),'edit-album':()=>openAlbumDialog(currentAlbum()),'delete-album':deleteAlbum,'add-album-media':()=>$('albumMediaDialog').showModal(),'add-farm':()=>openFarmDialog(),
 'open-farm':b=>openFarm(b.dataset.id),'edit-farm':()=>openFarmDialog(farm()),'open-strategy':()=>{renderStrategy();show('strategyView')},
 'open-memories':()=>{S.tag='all';renderMemories();show('memoryListView')},'edit-strategy':openStrategyDialog,'add-memory':()=>openMemoryDialog(),
 'open-memory':b=>openMemory(b.dataset.id),'edit-memory':()=>openMemoryDialog(memory()),'delete-memory':deleteMemory,
 'add-piano':()=>$('pianoDialog').showModal(),'add-guide':()=>$('guideDialog').showModal(),'open-media':b=>openViewer(b.dataset.id,b.dataset.scope),'edit-guide-media':openGuideEdit,
 'close-viewer':()=>$('viewerDialog').close(),'viewer-prev':()=>moveViewer(-1),'viewer-next':()=>moveViewer(1),'delete-piano-media':deleteViewerFile,
 'filter-tag':b=>{S.tag=b.dataset.tag;renderMemories()},'delete-farm':deleteFarm
};

function show(id,push=true){if(push&&S.view!==id)S.stack.push(S.view);S.view=id;VIEWS.forEach(v=>$(v).hidden=v!==id);const titles={homeView:'おうちアルバム',genericAlbumView:currentAlbum()?.name||'アルバム',pianoView:'ピアノ',farmListView:'Stardew Valley',farmView:farm()?.name||'牧場',strategyView:'攻略',memoryListView:'思い出',memoryDetailView:memory()?.title||'思い出'};$('pageTitle').textContent=titles[id];$('backButton').textContent=id==='homeView'?'‹':'‹';renderAll();window.scrollTo({top:0,behavior:'smooth'});}
function goBack(){if(S.view==='homeView'){location.href='../mama.html';return}const target=S.stack.pop()||'homeView';show(target,false);}
function farm(){return S.farms.find(x=>x.id===S.farmId)}function memory(){return S.memories.find(x=>x.id===S.memoryId)}
function renderAll(){renderAlbums();renderGenericAlbum();renderFarms();renderFarm();renderPiano();renderGuide();if(S.farmId){renderStrategy();renderMemories()}if(S.memoryId)renderMemoryDetail();}

function currentAlbum(){return S.albums.find(x=>x.id===S.albumId)}
function albumMedia(){return S.albumFiles.filter(x=>x.albumId===S.albumId).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
function renderAlbums(){const grid=$('albumRootGrid');if(!grid)return;grid.querySelectorAll('[data-user-album]').forEach(x=>x.remove());S.albums.forEach(a=>{const b=node('button','root-card custom-album');b.type='button';b.dataset.action='open-album';b.dataset.id=a.id;b.dataset.userAlbum='1';b.innerHTML=`<span>${esc(a.icon||'🎮')}</span><strong>${esc(a.name)}</strong><small>${esc(a.description||'写真・動画アルバム')}</small>`;grid.append(b);});}
function renderGenericAlbum(){const a=currentAlbum();if(!a)return;$('genericAlbumIcon').textContent=a.icon||'🎮';$('genericAlbumName').textContent=a.name;$('genericAlbumDescription').textContent=a.description||'写真・動画アルバム';const list=albumMedia();$('genericAlbumGrid').replaceChildren(...list.map(f=>mediaCard(f,'album')));$('genericAlbumEmpty').hidden=list.length>0;}
function openAlbum(id){S.albumId=id;renderGenericAlbum();show('genericAlbumView')}
function openAlbumDialog(a=null){$('albumForm').reset();$('albumId').value=a?.id||'';$('albumDialogTitle').textContent=a?'アルバムを編集':'新しいアルバム';$('albumDeleteButton').hidden=!a;if(a){$('albumName').value=a.name;$('albumIcon').value=a.icon||'';$('albumDescription').value=a.description||'';}$('albumDialog').showModal();}
async function saveAlbum(e){e.preventDefault();const id=$('albumId').value||`album-${crypto.randomUUID()}`,old=S.albums.find(x=>x.id===id),a={id,name:$('albumName').value.trim(),icon:$('albumIcon').value.trim()||'🎮',description:$('albumDescription').value.trim(),createdAt:old?.createdAt||new Date().toISOString()};await dbPut('albums',a);upsert(S.albums,a);S.albumId=id;$('albumDialog').close();renderAll();show('genericAlbumView');toast('アルバムを保存しました');}
async function deleteAlbum(){const a=currentAlbum();if(!a||!confirm(`${a.name}と中の写真・動画を削除しますか？`))return;for(const f of S.albumFiles.filter(x=>x.albumId===a.id))await dbDelete('albumFiles',f.id);await dbDelete('albums',a.id);S.albumFiles=S.albumFiles.filter(x=>x.albumId!==a.id);S.albums=S.albums.filter(x=>x.id!==a.id);S.albumId=null;$('albumDialog').close();show('homeView',false);toast('アルバムを削除しました');}
async function saveAlbumMedia(e){e.preventDefault();const chosen=[...$('albumMediaFiles').files],note=$('albumMediaNote').value.trim();if(!chosen.length||!S.albumId)return;try{for(const chosenFile of chosen){const file=await makeLocalFile(chosenFile,{ownerType:'album',ownerId:S.albumId,albumId:S.albumId,note});await dbPut('albumFiles',file.raw);S.albumFiles.unshift(file.view);}$('albumMediaDialog').close();$('albumMediaForm').reset();renderGenericAlbum();toast(`${chosen.length}件 保存しました`);}catch(err){console.error(err);toast('保存できませんでした');}}

function renderFarms(){$('farmCount').textContent=`${S.farms.length}個の牧場`;$('farmGrid').replaceChildren(...S.farms.map(f=>{const b=node('button','farm-card');b.dataset.action='open-farm';b.dataset.id=f.id;const names=[f.mama&&`ママ：${f.mama}`,f.eldest&&`長女：${f.eldest}`,f.youngest&&`次女：${f.youngest}`].filter(Boolean).join('　');b.innerHTML=`<span class="farm-sprout">🌱</span><span class="farm-card-copy"><strong>${esc(f.name)}</strong><small>${f.year?`${f.year}年目`:'年数未設定'}${f.main?`・${esc(f.main)}メイン`:''}</small>${names?`<em>${esc(names)}</em>`:''}</span><span class="chevron">›</span>`;return b;}));}
function renderFarm(){const f=farm();if(!f)return;const chars=[['ママ',f.mama],['長女',f.eldest],['次女',f.youngest]].map(([r,n])=>`<div><small>${r}</small><strong>${esc(n||'未設定')}</strong></div>`).join('');$('farmProfile').innerHTML=`<div class="farm-profile-top"><div><p class="eyebrow">${f.main?`${esc(f.main)}メイン`:'メイン未設定'}</p><h2>🌱 ${esc(f.name)}</h2><span>${f.year?`${f.year}年目`:'年数未設定'}</span></div><button class="small-button" data-action="edit-farm">編集</button></div><div class="character-grid">${chars}</div>${f.note?`<p class="farm-note">${nl(f.note)}</p>`:''}`;const st=strategy();$('strategySummary').textContent=`パーフェクション ${st.perfection||0}%・${CHECKS.filter(([k])=>st[k]).length}/${CHECKS.length}達成`;$('memorySummary').textContent=`${farmMemories().length}件の思い出`;
}
function openFarm(id){S.farmId=id;S.memoryId=null;renderFarm();show('farmView')}
function openFarmDialog(f=null){$('farmForm').reset();$('farmId').value=f?.id||'';$('farmDialogTitle').textContent=f?'牧場プロフィールを編集':'牧場を追加';if(f){$('farmName').value=f.name;$('farmMain').value=f.main||'';$('farmMama').value=f.mama||'';$('farmEldest').value=f.eldest||'';$('farmYoungest').value=f.youngest||'';$('farmYear').value=f.year||'';$('farmNote').value=f.note||'';}$('farmDialog').showModal();}
async function saveFarm(e){e.preventDefault();const id=$('farmId').value||`farm-${crypto.randomUUID()}`,old=S.farms.find(x=>x.id===id),f={id,name:$('farmName').value.trim(),main:$('farmMain').value,mama:$('farmMama').value.trim(),eldest:$('farmEldest').value.trim(),youngest:$('farmYoungest').value.trim(),year:$('farmYear').value?Number($('farmYear').value):'',note:$('farmNote').value.trim(),createdAt:old?.createdAt||new Date().toISOString()};await persist('farms',f,'/api/album/farms');upsert(S.farms,f);$('farmDialog').close();renderAll();toast('牧場を保存しました');}
async function deleteFarm(){const f=farm();if(!f||!confirm(`${f.name}と、その攻略・思い出をすべて削除しますか？`))return;if(S.cloud)await api(`/api/album/farms/${f.id}`,{method:'DELETE'});else{await dbDelete('farms',f.id);await dbDelete('strategy',f.id);for(const m of S.memories.filter(x=>x.farmId===f.id))await dbDelete('memories',m.id);for(const file of S.files.filter(x=>x.farmId===f.id))await dbDelete('files',file.id)}S.farms=S.farms.filter(x=>x.id!==f.id);S.strategies=S.strategies.filter(x=>x.farmId!==f.id);S.memories=S.memories.filter(x=>x.farmId!==f.id);S.files=S.files.filter(x=>x.farmId!==f.id);S.farmId=null;show('farmListView',false);toast('牧場を削除しました');}

function strategy(){return S.strategies.find(x=>x.farmId===S.farmId)||{farmId:S.farmId,perfection:0,note:''}}
function renderStrategy(){const f=farm(),s=strategy();if(!f)return;$('strategyFarmName').textContent=f.name;$('perfectionValue').textContent=`${Number(s.perfection||0)}%`;$('perfectionBar').value=Number(s.perfection||0);$('strategyGrid').replaceChildren(...CHECKS.map(([k,icon,label])=>{const d=node('article',`strategy-item ${s[k]?'done':''}`);d.innerHTML=`<span>${s[k]?'✅':icon}</span><strong>${label}</strong><small>${s[k]?'達成':'これから'}</small>`;return d;}));$('strategyNote').innerHTML=s.note?nl(s.note):'まだメモはありません。';}
function openStrategyDialog(){const s=strategy();$('strategyPerfection').value=s.perfection||0;$('strategyMemo').value=s.note||'';$('strategyChecks').replaceChildren(nodeHtml('legend','','達成したもの'),...CHECKS.map(([k,icon,label])=>{const l=node('label','check-row');l.innerHTML=`<input type="checkbox" data-check="${k}" ${s[k]?'checked':''}><span>${icon} ${label}</span>`;return l;}));$('strategyDialog').showModal();}
async function saveStrategy(e){e.preventDefault();const s={farmId:S.farmId,perfection:Math.min(100,Math.max(0,Number($('strategyPerfection').value||0))),note:$('strategyMemo').value.trim()};CHECKS.forEach(([k])=>s[k]=Boolean(document.querySelector(`[data-check="${k}"]`)?.checked));await persist('strategy',s,`/api/album/strategy/${S.farmId}`,'PUT');upsert(S.strategies,s,'farmId');$('strategyDialog').close();renderAll();toast('攻略を更新しました');}

function farmMemories(){return S.memories.filter(x=>x.farmId===S.farmId).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
function renderMemories(){const f=farm();if(!f)return;$('memoryFarmName').textContent=f.name;const all=farmMemories(),tags=[...new Set(all.flatMap(x=>x.tags||[]))];$('tagFilters').replaceChildren(tagButton('all','すべて'),...tags.map(t=>tagButton(t,`#${t}`)));const list=S.tag==='all'?all:all.filter(x=>(x.tags||[]).includes(S.tag));$('memoryGrid').replaceChildren(...list.map(m=>{const files=memoryFiles(m.id),cover=files[0],b=node('button','memory-card');b.dataset.action='open-memory';b.dataset.id=m.id;const media=cover?mediaNode(cover,false):nodeHtml('div','memory-placeholder','<span>📷</span><small>写真未登録</small>');const timing=gameDate(m)||formatDate(m.createdAt);const tagsHtml=(m.tags||[]).slice(0,3).map(t=>`<span>#${esc(t)}</span>`).join('');const wrap=node('span','memory-cover');wrap.append(media);b.append(wrap,nodeHtml('span','memory-card-copy',`<strong>${esc(m.title)}</strong><small>${esc(timing)}</small><span class="memory-tags">${tagsHtml}</span>`));return b;}));$('memoryEmpty').hidden=list.length>0;}
function tagButton(tag,label){const b=node('button',`tag-filter ${S.tag===tag?'active':''}`);b.dataset.action='filter-tag';b.dataset.tag=tag;b.textContent=label;return b;}
function openMemory(id){S.memoryId=id;renderMemoryDetail();show('memoryDetailView')}
function renderMemoryDetail(){const m=memory();if(!m)return;const tags=(m.tags||[]).map(t=>`<span>#${esc(t)}</span>`).join(''),people=(m.participants||[]).join('・');$('memoryDetailHead').innerHTML=`<p class="eyebrow">${esc(farm()?.name||'')}</p><h2>${esc(m.title)}</h2><p>${esc(gameDate(m)||formatDate(m.createdAt))}${people?`　👥 ${esc(people)}`:''}</p><div class="memory-tags">${tags}</div>`;$('memoryDetailMedia').replaceChildren(...memoryFiles(m.id).map(file=>{const b=node('button','detail-media');b.dataset.action='open-media';b.dataset.id=file.id;b.dataset.scope='memory';b.append(mediaNode(file,false));return b;}));$('memoryDetailStory').innerHTML=m.story?nl(m.story):'説明はまだありません。';}
function openMemoryDialog(m=null){$('memoryForm').reset();$('memoryId').value=m?.id||'';$('memoryDialogTitle').textContent=m?'思い出を編集':'思い出を追加';$('memoryFilesLabel').querySelector('small').textContent=m?'追加する写真・動画があれば選択（今の画像は残ります）':'iPhoneからそのまま選べます';if(m){$('memoryTitle').value=m.title;$('memoryYear').value=m.gameYear||'';$('memorySeason').value=m.season||'';$('memoryDay').value=m.day||'';$('memoryTags').value=(m.tags||[]).join('、');$('memoryStory').value=m.story||'';document.querySelectorAll('.participant-checks input').forEach(x=>x.checked=(m.participants||[]).includes(x.value));}$('memoryDialog').showModal();}
async function saveMemory(e){e.preventDefault();const chosen=[...$('memoryFiles').files];if(!$('memoryId').value&&!chosen.length){toast('写真か動画を1つ以上選んでね');return}const old=memory(),id=$('memoryId').value||`memory-${crypto.randomUUID()}`,m={id,farmId:S.farmId,title:$('memoryTitle').value.trim(),gameYear:$('memoryYear').value?Number($('memoryYear').value):'',season:$('memorySeason').value,day:$('memoryDay').value?Number($('memoryDay').value):'',participants:[...document.querySelectorAll('.participant-checks input:checked')].map(x=>x.value),tags:splitTags($('memoryTags').value),story:$('memoryStory').value.trim(),createdAt:old?.createdAt||new Date().toISOString()};setProgress(true,0);try{if(S.cloud){const form=memoryFormData(m,chosen);const result=await api(old?`/api/album/memories/${id}`:'/api/album/memories',{method:old?'PATCH':'POST',body:form});upsert(S.memories,result.memory);mergeCloudFiles(result.files||[]);}else{await dbPut('memories',m);upsert(S.memories,m);for(let i=0;i<chosen.length;i++){const file=await makeLocalFile(chosen[i],{ownerType:'memory',ownerId:id,farmId:S.farmId});await dbPut('files',file.raw);S.files.push(file.view);setProgress(true,Math.round((i+1)/chosen.length*100));}}$('memoryDialog').close();S.memoryId=id;renderAll();toast('思い出を保存しました');}catch(err){console.error(err);toast('保存できませんでした');}finally{setProgress(false,0);}}
async function deleteMemory(){const m=memory();if(!m||!confirm('この思い出と写真・動画を削除しますか？'))return;if(S.cloud)await api(`/api/album/memories/${m.id}`,{method:'DELETE'});else{await dbDelete('memories',m.id);for(const f of memoryFiles(m.id))await dbDelete('files',f.id);}S.memories=S.memories.filter(x=>x.id!==m.id);S.files=S.files.filter(x=>x.ownerId!==m.id);S.memoryId=null;show('memoryListView',false);toast('思い出を削除しました');}
function memoryFiles(id){return S.files.filter(x=>x.ownerType==='memory'&&x.ownerId===id)}

function renderPiano(){let list=S.piano;if(S.pianoFilter!=='all')list=list.filter(x=>x.kind===S.pianoFilter);$('pianoGrid').replaceChildren(...list.map(f=>mediaCard(f,'piano')));$('pianoEmpty').hidden=list.length>0;}
function renderGuide(){const list=S.guides.length?S.guides:GUIDE;$('stardewGuideGrid').replaceChildren(...list.map(f=>mediaCard(f,'guide')))}
function mediaCard(f,scope){const b=node('button','media-card');b.dataset.action='open-media';b.dataset.id=f.id;b.dataset.scope=scope;b.append(mediaNode(f,false));b.insertAdjacentHTML('beforeend',`<span class="media-badges">${f.kind==='video'?'<span class="media-badge">▶</span>':''}</span><span class="media-note">${esc(f.note||f.name||'')}</span>`);return b;}
async function savePiano(e){e.preventDefault();const chosen=[...$('pianoFiles').files],note=$('pianoNote').value.trim();if(!chosen.length)return;try{if(S.cloud){for(const file of chosen){const form=new FormData();form.append('file',file);form.append('note',note);const out=await api('/api/album/piano',{method:'POST',body:form});S.piano.unshift(normalizeFile(out));}}else{for(const chosenFile of chosen){const file=await makeLocalFile(chosenFile,{ownerType:'piano',ownerId:'piano',note});await dbPut('piano',file.raw);S.piano.unshift(file.view);}}$('pianoDialog').close();$('pianoForm').reset();renderPiano();toast(`${chosen.length}件 保存しました`);}catch(err){console.error(err);toast('保存できませんでした');}}
async function saveGuide(e){e.preventDefault();const file=$('guideFile').files[0],note=$('guideNote').value.trim();if(!file||!note)return;try{if(S.cloud){const form=new FormData();form.append('file',file);form.append('note',note);S.guides.unshift(normalizeFile(await api('/api/album/guides',{method:'POST',body:form})));}else{const saved=await makeLocalFile(file,{ownerType:'piano',ownerId:'stardew-guide',note});await dbPut('guides',saved.raw);S.guides.unshift(saved.view);}$('guideDialog').close();$('guideForm').reset();renderGuide();toast('攻略資料を追加しました');}catch(err){console.error(err);toast('保存できませんでした');}}
function openGuideEdit(){const f=S.viewer[S.viewerIndex];if(!f||f.seed)return;$('viewerDialog').close();$('guideEditId').value=f.id;$('guideEditNote').value=f.note||f.name||'';$('guideEditDialog').showModal();}
async function saveGuideTitle(e){e.preventDefault();const guideId=$('guideEditId').value,note=$('guideEditNote').value.trim(),f=S.guides.find(x=>x.id===guideId);if(!f||!note)return;try{if(S.cloud)await api(`/api/album/files/${guideId}`,{method:'PATCH',body:JSON.stringify({note})});else{f.note=note;await dbPut('guides',{...f,blob:f.blob,url:undefined});}f.note=note;$('guideEditDialog').close();renderGuide();toast('タイトルを更新しました');}catch(err){console.error(err);toast('更新できませんでした');}}
function openViewer(id,scope){S.viewerScope=scope;S.viewer=scope==='piano'?S.piano:scope==='album'?albumMedia():scope==='guide'?(S.guides.length?S.guides:GUIDE):memoryFiles(S.memoryId);S.viewerIndex=S.viewer.findIndex(x=>x.id===id);const f=S.viewer[S.viewerIndex];S.viewerDelete=(scope==='piano'||scope==='album'||(scope==='guide'&&!f?.seed))?id:null;renderViewer();$('viewerDialog').showModal();}
function renderViewer(){const f=S.viewer[S.viewerIndex];if(!f)return;$('viewerStage').replaceChildren(mediaNode(f,true));$('viewerName').textContent=f.note||f.name||'';$('viewerCounter').textContent=`${S.viewerIndex+1} / ${S.viewer.length}`;$('viewerEdit').hidden=S.viewerScope!=='guide'||Boolean(f.seed);document.querySelector('[data-action="delete-piano-media"]').hidden=!S.viewerDelete;}
function moveViewer(n){if(!S.viewer.length)return;S.viewerIndex=(S.viewerIndex+n+S.viewer.length)%S.viewer.length;const f=S.viewer[S.viewerIndex];S.viewerDelete=(S.viewerScope==='piano'||S.viewerScope==='album'||(S.viewerScope==='guide'&&!f?.seed))?f.id:null;renderViewer();}
async function deleteViewerFile(){const f=S.viewer[S.viewerIndex];if(!f||f.seed||!confirm('この写真・動画を削除しますか？'))return;if(S.viewerScope==='album'){await dbDelete('albumFiles',f.id);S.albumFiles=S.albumFiles.filter(x=>x.id!==f.id);renderGenericAlbum()}else{if(S.cloud)await api(`/api/album/files/${f.id}`,{method:'DELETE'});else await dbDelete(S.viewerScope==='guide'?'guides':'piano',f.id);if(S.viewerScope==='guide'){S.guides=S.guides.filter(x=>x.id!==f.id);renderGuide()}else{S.piano=S.piano.filter(x=>x.id!==f.id);renderPiano()}}$('viewerDialog').close();toast('削除しました');}

function gameDate(m){return [m.gameYear&&`${m.gameYear}年目`,m.season,m.day&&`${m.day}日`].filter(Boolean).join(' ')||''}
function mediaNode(f,controls){const x=document.createElement(f.kind==='video'?'video':'img');x.src=f.url;if(f.kind==='video'){x.playsInline=true;x.preload='metadata';x.controls=controls;if(!controls)x.muted=true}else{x.alt=f.note||f.name||'';x.loading='lazy'}return x;}
function splitTags(s){return [...new Set(String(s||'').split(/[、,，\s]+/).map(x=>x.trim().replace(/^#/,'')).filter(Boolean))].slice(0,20)}
function setProgress(on,n){$('uploadProgress').hidden=!on;$('memorySaveButton').disabled=on;$('uploadProgressBar').value=n;$('uploadProgressText').textContent=`保存しています… ${n}%`;}
function memoryFormData(m,files){const form=new FormData();form.append('meta',JSON.stringify(m));files.forEach(f=>form.append('files',f));return form;}

async function loadLocal(){S.albums=await dbAll('albums');S.albumFiles=(await dbAll('albumFiles')).map(localView);S.farms=await dbAll('farms');S.strategies=await dbAll('strategy');S.memories=await dbAll('memories');S.files=(await dbAll('files')).map(localView);S.piano=(await dbAll('piano')).map(localView);S.guides=(await dbAll('guides')).map(localView);}
async function ensureSeeds(){if(!S.farms.length){for(const f of SEED_FARMS){await dbPut('farms',f);S.farms.push(f)}}if(!localStorage.getItem('wagaya_album_v2_seeded')){for(const m of SEED_MEMORIES){if(!S.memories.some(x=>x.id===m.id)){await dbPut('memories',m);S.memories.push(m)}}localStorage.setItem('wagaya_album_v2_seeded','1')}}
async function persist(store,obj,path,method='POST'){if(S.cloud){const saved=await api(path,{method,body:JSON.stringify(obj)});Object.assign(obj,saved||{})}else await dbPut(store,obj)}
async function remove(store,id,path){if(S.cloud)await api(path,{method:'DELETE'});else await dbDelete(store,id)}
async function makeLocalFile(file,extra){const raw={id:`file-${crypto.randomUUID()}`,kind:file.type.startsWith('video/')?'video':'image',name:file.name,mimeType:file.type,size:file.size,blob:file,createdAt:new Date().toISOString(),...extra};return{raw,view:localView(raw)}}
function localView(raw){return{...raw,url:URL.createObjectURL(raw.blob),local:true}}
function normalizeFile(f){return{...f,url:f.url?.startsWith('http')?f.url:`${API}${f.url}`,favorite:Boolean(f.favorite),cloud:true}}
function mergeCloudFiles(files){for(const f of files)upsert(S.files,normalizeFile(f))}
async function syncCloud(quiet=false){try{const data=await api('/api/album/bootstrap');S.cloud=true;S.farms=data.farms||[];S.strategies=data.strategies||[];S.memories=data.memories||[];S.files=(data.files||[]).filter(x=>x.ownerType==='memory').map(normalizeFile);S.piano=(data.files||[]).filter(x=>x.ownerType==='piano'&&x.ownerId==='piano').map(normalizeFile);let guideRows=(data.files||[]).filter(x=>x.ownerType==='piano'&&x.ownerId==='stardew-guide');if(!guideRows.length){try{guideRows=(await api('/api/album/guides/seed',{method:'POST'})).files||[]}catch(err){console.warn('guide seed failed',err)}}S.guides=guideRows.map(normalizeFile);renderAll();updateStorage();}catch(e){S.cloud=false;updateStorage();if(!quiet)throw e}}
async function saveSettings(e){e.preventDefault();const value=$('accessKeyInput').value.trim();value?localStorage.setItem(ACCESS,value):localStorage.removeItem(ACCESS);if(!API){$('settingsDialog').close();updateStorage();toast('現在はこの端末に保存します');return}try{await syncCloud();$('settingsDialog').close();toast('クラウドにつながりました')}catch{toast('合言葉か接続設定を確認してね')}}
async function api(path,opt={}){const h=new Headers(opt.headers||{});h.set('X-Album-Key',key());if(opt.body&&!(opt.body instanceof FormData))h.set('Content-Type','application/json');const r=await fetch(`${API}${path}`,{...opt,headers:h,cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.status===204?null:r.json()}
function key(){return localStorage.getItem(ACCESS)||''}function updateStorage(){if(!API){$('storageStatus').textContent='📱 現在はこの端末に保存します。Worker設定後は家族端末で共有できます。';$('accessKeyLabel').hidden=true}else{$('accessKeyLabel').hidden=false;$('storageStatus').textContent=S.cloud?'☁️ クラウド保存につながっています。':'📱 端末保存中。合言葉でクラウド接続できます。'}}

function openDb(){if(dbp)return dbp;dbp=new Promise((ok,no)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{['albums','albumFiles','farms','strategy','memories','files','piano','guides'].forEach(name=>{if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name,{keyPath:name==='strategy'?'farmId':'id'})})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return dbp}
async function dbAct(store,mode,fn){const db=await openDb();return new Promise((ok,no)=>{const r=fn(db.transaction(store,mode).objectStore(store));r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}const dbAll=s=>dbAct(s,'readonly',x=>x.getAll()),dbPut=(s,v)=>dbAct(s,'readwrite',x=>x.put(v)),dbDelete=(s,k)=>dbAct(s,'readwrite',x=>x.delete(k));
function upsert(list,obj,keyName='id'){const i=list.findIndex(x=>x[keyName]===obj[keyName]);i<0?list.push(obj):list.splice(i,1,obj)}function node(tag,cls=''){const x=document.createElement(tag);x.className=cls;return x}function nodeHtml(tag,cls,html){const x=node(tag,cls);x.innerHTML=html;return x}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function nl(v){return esc(v).replace(/\n/g,'<br>')}function formatDate(v){const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'short',day:'numeric'}).format(d)}function toast(msg){clearTimeout(toastTimer);$('toast').textContent=msg;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
})();
